#! /bin/sh

# Abort if any command returns an error value
set -e

case "$1" in
    purge|remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
	# remove kernel symlinks
	rm -f /boot/pve/vmlinuz
	rm -f /boot/pve/initrd.img
	rmdir --ignore-fail-on-non-empty /boot/pve/ || true
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

