name: Kernel Build (Trusted)

on: pull_request

jobs:
  build:
    name: Build
    runs-on: [self-hosted]
    strategy:
      matrix:
        include:
          - build_cc: gcc-10
    if: github.event.pull_request.head.repo.full_name == github.repository && !contains(github.event.head_commit.message, 'skip ci')
    steps:
    - name: Checkout Sources
      uses: actions/checkout@v2
      with:
          submodules: recursive
    - name: Build Kernel
      run: make
      env:
          PVE_BUILD_CC: ${{ matrix.build_cc }}
    - name: Read Build Information
      id: read_build_info
      run: |
        echo "::set-output name=release::$(sed '1q;d' release.txt)"
        echo "::set-output name=dst::$(sed '1q;d' artifacts.txt)"
        echo "::set-output name=hdr::$(sed '2q;d' artifacts.txt)"
        echo "::set-output name=tools::$(sed '3q;d' artifacts.txt)"
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2-preview
      with:
        name: debs-${{ matrix.build_type }}
        path: "*.deb"

